-- 050_office_dashboard.sql
-- Creates tables for the 3D Agent Office Dashboard.
--
-- Tables:
--   agent_office_state  — current state of each agent in the office
--   quest_log           — policy gate decisions surfaced as quests
--   daily_memo          — daily per-department activity summaries
--   command_audit_log   — audit trail for all command center mutations
--
-- All tables follow the existing tenant isolation pattern:
--   tenant_id -> tenants(id) with RLS using current_tenant_id()

-- ============================================================================
-- AGENT OFFICE STATE
-- ============================================================================
-- Tracks the current LangGraph state of each agent character in the 3D office.
-- Upserted by Inngest functions on calllock/agent.state.changed events.
-- Read by the dashboard via Supabase Realtime subscription.

create table public.agent_office_state (
  agent_id   text        not null,
  tenant_id  uuid        not null references public.tenants(id) on delete cascade,
  department text        not null,
  role       text        not null,
  supervisor_id text,
  current_state text     not null default 'idle',
  description   text,
  call_id       text,
  updated_at    timestamptz not null default now(),
  primary key (tenant_id, agent_id)
);

alter table public.agent_office_state enable row level security;
alter table public.agent_office_state force row level security;

create policy tenant_isolation on public.agent_office_state
  using (tenant_id = public.current_tenant_id());

-- Index for department-level queries (office room view)
create index idx_agent_office_state_dept
  on public.agent_office_state (tenant_id, department);

-- ============================================================================
-- QUEST LOG
-- ============================================================================
-- Policy gate decisions surfaced as actionable quests in the Central Lobby.
-- Created by calllock/policy.gate.pending events.
-- Resolved via the command center /api/quest/resolve endpoint.

create table public.quest_log (
  id          uuid        primary key default gen_random_uuid(),
  tenant_id   uuid        not null references public.tenants(id) on delete cascade,
  agent_id    text        not null,
  department  text        not null,
  call_id     text,
  rule_violated text      not null,
  summary     text        not null,
  options     jsonb       not null default '[]'::jsonb,
  urgency     text        not null default 'medium',
  status      text        not null default 'pending',
  resolution  text,
  resolved_by text,
  created_at  timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.quest_log enable row level security;
alter table public.quest_log force row level security;

create policy tenant_isolation on public.quest_log
  using (tenant_id = public.current_tenant_id());

-- Fast lookup for pending quests (quest log kiosk)
create index idx_quest_log_pending
  on public.quest_log (tenant_id, status)
  where status = 'pending';

-- Chronological listing (resolved today section)
create index idx_quest_log_created
  on public.quest_log (tenant_id, created_at desc);

-- ============================================================================
-- DAILY MEMO
-- ============================================================================
-- Per-department activity summaries displayed on the lobby memo board.
-- Generated by Inngest cron (calllock/memo.daily.generate) at midnight.
-- Content is a structured JSON object with department sections.

create table public.daily_memo (
  id          uuid        primary key default gen_random_uuid(),
  tenant_id   uuid        not null references public.tenants(id) on delete cascade,
  memo_date   date        not null,
  content     jsonb       not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  unique (tenant_id, memo_date)
);

alter table public.daily_memo enable row level security;
alter table public.daily_memo force row level security;

create policy tenant_isolation on public.daily_memo
  using (tenant_id = public.current_tenant_id());

-- ============================================================================
-- COMMAND AUDIT LOG
-- ============================================================================
-- Every mutation through the command center is logged for debugging,
-- compliance, and accountability. Append-only.

create table public.command_audit_log (
  id          uuid        primary key default gen_random_uuid(),
  tenant_id   uuid        not null references public.tenants(id) on delete cascade,
  user_id     uuid        not null,
  action_type text        not null,
  target_agent text,
  payload     jsonb       not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.command_audit_log enable row level security;
alter table public.command_audit_log force row level security;

create policy tenant_isolation on public.command_audit_log
  using (tenant_id = public.current_tenant_id());

-- Fast lookup for recent audit entries
create index idx_audit_log_tenant_created
  on public.command_audit_log (tenant_id, created_at desc);

-- Filter by action type (e.g., show all quest resolutions)
create index idx_audit_log_action_type
  on public.command_audit_log (tenant_id, action_type);
